[[headers]]
  for = "/*"
  [headers.values]
    ACCESS-CONTROL-ALLOW-ORIGIN = "*"
[build]
  publish = "build"
  command = "npm run build"
[context.production.environment]
  NODE_ENV = "production"
  VITE_API_URL = "https://groenkeurapi.erkenningen.nl/api"
  VITE_API_KEY = "81553e36-9ca2-4e58-8875-2dea779da509"
[context.acceptance.environment]
  NODE_ENV = "production"
  VITE_API_URL = "https://groenkeurapi.acceptatie.erkenningen.nl/api"
  VITE_API_KEY = "fc7b6bdc-50e4-4914-b084-b4f009d3fd60"
[context.deploy-preview.environment]
  NODE_ENV = "production"
  VITE_API_URL = "https://groenkeurapi.acceptatie.erkenningen.nl/api"
  VITE_API_KEY = "fc7b6bdc-50e4-4914-b084-b4f009d3fd60"